import Hurst.ShiftedWeightEnergy
import Mathlib.Analysis.Normed.Group.Tannery
#check tsum_eq_sum
#check tsum_eq_sum'
#check HasSum.tsum_eq
#check hasSum_iff_eventually_eq
#check summable_of_ne_finset_zero
#check Finset.hasSum_sum
#check hasSum_fintype
#check Finset.sum_filter
#check Finset.sum_product
#check Finset.sum_diag
#check Finset.diag
#check Finset.offDiag
#check Finset.sum_union
#check Finset.sum_product'
#check Nat.sub_lt
#check Nat.sub_add_cancel
#check Prod.ext
#check Fin.sum_univ_eq_sum_range
