import Hurst.ShiftedWeightEnergy
#check HasDerivAt.lipschitzOnWith_of_nnnorm_deriv_le
#check HasDerivAt.lipschitzOnWith_of_abs_deriv_le
#check LipschitzWith.of_deriv_le
#check LipschitzOnWith.of_deriv_le
#check Convex.lipschitzOnWith_of_nnnorm_deriv_le
#check Convex.lipschitzOnWith_of_norm_hasFDerivWithin_le
#check lipschitzWith_iff_norm_sub_le
#check HasCompactSupport.exists_bound_of_continuousOn
#check HasCompactSupport.deriv
#check ContDiff.deriv
#check Metric.lipschitzWith_iff_dist_le_mul
#check LipschitzWith.of_dist_le_mul
#check lipschitzOnWith_univ
#check lipschitzWith_iff_lipschitzOnWith_univ
#check NNReal.coe_le_coe
#check NNReal.coe_toNNReal
#check Real.toNNReal_of_nonneg
#check nnnorm_of_nonneg
#check Real.nnnorm_of_nonneg
#check LipschitzWith.dist_le_mul
#check LipschitzWith.norm_sub_le
