import Hurst.ActualCommonCutoffAveragedMoment
#check MeasureTheory.integral_mono_ae
#check MeasureTheory.Integrable.abs
#check MeasureTheory.MemLp.integrable
#check MeasureTheory.MemLp.integrable_norm_rpow
#check MeasureTheory.MemLp.integrable_norm_rpow'
#check MeasureTheory.Integrable.const_mul
#check MeasureTheory.integral_add
#check MeasureTheory.integral_const_mul
#check Even.add_pow_le
#check abs_pow
#check MeasureTheory.Integrable.mono'
#check MeasureTheory.Integrable.add
#check abs_sub_le_abs_sub_add_abs_sub
#check abs_sub_comm
#check abs_sub
#check abs_sub_le_iff
#check abs_sub_le_iff.2
#check Real.rpow_natCast
#check MeasureTheory.Integrable.pow
#check MeasureTheory.Integrable.norm
#check pow_sum_le_card_mul_sum_pow
#check Finset.aestronglyMeasurable_sum
#check AEStronglyMeasurable.finset_sum
#check AEStronglyMeasurable.finsetSum
