import Hurst.FeatureRestriction
import Hurst.FeatureStandardGaussian
import Hurst.FeatureHermiteApproximation
import Hurst.FeatureHermiteTests
import Mathlib.MeasureTheory.Function.ConvergenceInDistribution

noncomputable section
open MeasureTheory ProbabilityTheory Matrix
open scoped RealInnerProductSpace ENNReal
namespace Hurst

variable {ι κ E : Type*} [Fintype ι] [DecidableEq ι]
  [Fintype κ] [DecidableEq κ]
  [NormedAddCommGroup E] [InnerProductSpace ℝ E]

def standardizedFeatureVector (v : ι → E)
    (a : EuclideanSpace ℝ ι) : E :=
  ‖∑ i, a i • v i‖⁻¹ • ∑ i, a i • v i

/-- The continuous linear map collecting a finite family of standardized
feature observations. -/
def standardizedFeatureObservationMap (v : ι → E)
    (a : κ → EuclideanSpace ℝ ι) :
    EuclideanSpace ℝ ι →L[ℝ] EuclideanSpace ℝ κ :=
  (PiLp.continuousLinearEquiv 2 ℝ (fun _ : κ => ℝ)).symm.toContinuousLinearMap.comp
    (ContinuousLinearMap.pi fun k : κ =>
      ‖∑ i, a k i • v i‖⁻¹ • innerSL ℝ (a k))

@[simp]
theorem standardizedFeatureObservationMap_apply (v : ι → E)
    (a : κ → EuclideanSpace ℝ ι) (x : EuclideanSpace ℝ ι) (k : κ) :
    standardizedFeatureObservationMap v a x k =
      standardizedFeatureObservation v (a k) x := by
  simp [standardizedFeatureObservationMap, standardizedFeatureObservation,
    div_eq_mul_inv, mul_comm]

 theorem standardizedFeatureVector_inner (v : ι → E)
    (a b : EuclideanSpace ℝ ι) :
    ⟪standardizedFeatureVector v a, standardizedFeatureVector v b⟫ =
      featureCorrelation v a b := by
  simp only [standardizedFeatureVector, inner_smul_left, inner_smul_right,
    conj_trivial, smul_eq_mul, featureCorrelation]
  ring

/-- The joint law of standardized linear feature observations is exactly the
feature Gaussian generated by their normalized Hilbert-space feature vectors. -/
theorem featureGaussian_map_standardizedFeatureObservationMap
    (v : ι → E) (a : κ → EuclideanSpace ℝ ι) :
    (featureGaussian v).map (standardizedFeatureObservationMap v a) =
      featureGaussian (fun k => standardizedFeatureVector v (a k)) := by
  apply IsGaussian.ext
  · simp only [id_eq]
    rw [ContinuousLinearMap.integral_id_map]
    · simp [featureGaussian]
    · exact IsGaussian.integrable_id
  · rw [← ContinuousLinearMap.toBilinForm_inj]
    refine LinearMap.BilinForm.ext_basis (EuclideanSpace.basisFun κ ℝ).toBasis fun i j => ?_
    rw [ContinuousLinearMap.toBilinForm_apply, ContinuousLinearMap.toBilinForm_apply,
      covarianceBilin_apply_eq_cov IsGaussian.memLp_two_id,
      covarianceBilin_apply_eq_cov IsGaussian.memLp_two_id]
    simp only [OrthonormalBasis.coe_toBasis, EuclideanSpace.basisFun_inner]
    rw [covariance_map (by fun_prop) (by fun_prop) (by fun_prop)]
    have hi : ((fun u : EuclideanSpace ℝ κ => u i) ∘
        (standardizedFeatureObservationMap v a)) =
        standardizedFeatureObservation v (a i) := by
      funext x
      exact standardizedFeatureObservationMap_apply v a x i
    have hj : ((fun u : EuclideanSpace ℝ κ => u j) ∘
        (standardizedFeatureObservationMap v a)) =
        standardizedFeatureObservation v (a j) := by
      funext x
      exact standardizedFeatureObservationMap_apply v a x j
    rw [hi, hj, standardizedFeatureObservation_covariance,
      featureGaussian_covariance, standardizedFeatureVector_inner]

theorem norm_standardizedFeatureVector (v : ι → E)
    (a : EuclideanSpace ℝ ι) (ha : ∑ i, a i • v i ≠ 0) :
    ‖standardizedFeatureVector v a‖ = 1 := by
  unfold standardizedFeatureVector
  rw [norm_smul, Real.norm_eq_abs, abs_inv, abs_norm, inv_mul_cancel₀]
  exact norm_ne_zero_iff.mpr ha

/-- Once the selected feature vectors are normalized, standardization of a
coordinate projection is definitionally harmless. -/
theorem standardizedFeatureObservation_basis_normalized
    (u : κ → E) (hu : ∀ k, ‖u k‖ = 1)
    (x : EuclideanSpace ℝ κ) (k : κ) :
    standardizedFeatureObservation u (EuclideanSpace.basisFun κ ℝ k) x = x k := by
  unfold standardizedFeatureObservation
  have hsum : (∑ i, (EuclideanSpace.basisFun κ ℝ k) i • u i) = u k := by
    simp [EuclideanSpace.basisFun_apply]
  rw [hsum, hu k, div_one]
  exact EuclideanSpace.basisFun_inner κ ℝ x k

/-- The finite Hermite statistic factors pointwise through the joint
standardized-observation map. -/
theorem gaussianLogTruncationStatistic_factor_observationMap
    (v : ι → E) (w : κ → ℝ) (a : κ → EuclideanSpace ℝ ι)
    (M : ℕ) (x : EuclideanSpace ℝ ι) :
    gaussianLogTruncationStatistic v w a M x =
      ∑ k, w k * (hermiteTruncationPolynomial gaussianLogLp M).eval
        (standardizedFeatureObservationMap v a x k) := by
  unfold gaussianLogTruncationStatistic
  apply Finset.sum_congr rfl
  intro k hk
  rw [standardizedFeatureObservationMap_apply]

/-- With normalized feature vectors and coordinate coefficients, the same
finite Hermite statistic is the coordinate polynomial sum. -/
theorem gaussianLogTruncationStatistic_basis_normalized
    (u : κ → E) (hu : ∀ k, ‖u k‖ = 1) (w : κ → ℝ)
    (M : ℕ) (x : EuclideanSpace ℝ κ) :
    gaussianLogTruncationStatistic u w
        (fun k => EuclideanSpace.basisFun κ ℝ k) M x =
      ∑ k, w k * (hermiteTruncationPolynomial gaussianLogLp M).eval (x k) := by
  unfold gaussianLogTruncationStatistic
  apply Finset.sum_congr rfl
  intro k hk
  rw [standardizedFeatureObservation_basis_normalized u hu x k]

/-- Replacing the original Gaussian observation by the finite vector of its
standardized linear features preserves the law of the finite Hermite
statistic. -/
theorem gaussianLogTruncationStatistic_identDistrib_normalizedFeatures
    (v : ι → E) (w : κ → ℝ) (a : κ → EuclideanSpace ℝ ι)
    (ha : ∀ k, ∑ i, a k i • v i ≠ 0) (M : ℕ) :
    IdentDistrib
      (gaussianLogTruncationStatistic v w a M)
      (gaussianLogTruncationStatistic
        (fun k => standardizedFeatureVector v (a k)) w
        (fun k => EuclideanSpace.basisFun κ ℝ k) M)
      (featureGaussian v)
      (featureGaussian (fun k => standardizedFeatureVector v (a k))) := by
  let u : κ → E := fun k => standardizedFeatureVector v (a k)
  let L := standardizedFeatureObservationMap v a
  let F : EuclideanSpace ℝ κ → ℝ := fun x =>
    ∑ k, w k * (hermiteTruncationPolynomial gaussianLogLp M).eval (x k)
  have hu : ∀ k, ‖u k‖ = 1 := fun k => norm_standardizedFeatureVector v (a k) (ha k)
  have hactual : gaussianLogTruncationStatistic v w a M = F ∘ L := by
    funext x
    exact gaussianLogTruncationStatistic_factor_observationMap v w a M x
  have htarget : gaussianLogTruncationStatistic u w
      (fun k => EuclideanSpace.basisFun κ ℝ k) M = F := by
    funext x
    exact gaussianLogTruncationStatistic_basis_normalized u hu w M x
  have hLm : Measurable L := L.continuous.measurable
  have hFm : Measurable F := by
    dsimp only [F]
    fun_prop
  refine ⟨(gaussianLogTruncationStatistic_memLp_two v w a M).1.aemeasurable,
    (gaussianLogTruncationStatistic_memLp_two u w
      (fun k => EuclideanSpace.basisFun κ ℝ k) M).1.aemeasurable, ?_⟩
  rw [hactual, htarget, ← Measure.map_map hFm hLm,
    featureGaussian_map_standardizedFeatureObservationMap]

end Hurst
