/-
Adapted from StatLean/Stat-Lean, commit 855b6afb69fead1bef066111732ed44df181040e,
StatLean/Minimaxity/ForMathlib/KLDataProcessing.lean. Apache-2.0; see third_party/StatLean/LICENSE.
Local changes: namespace changed to Hurst.
-/
import Mathlib.InformationTheory.KullbackLeibler.ChainRule
import Mathlib.MeasureTheory.Function.ConditionalExpectation.CondJensen
import Mathlib.MeasureTheory.Function.ConditionalExpectation.RadonNikodym

/-!
# Data-processing inequality for KL divergence under a measurable map

For a measurable map $f : \alpha \to \beta$ and probability measures $\mu, \nu$ on $\alpha$, the
Kullback–Leibler divergence contracts under the push-forward (deterministic channel):
$$ D\!\left(\mu \circ f^{-1} \,\big\|\, \nu \circ f^{-1}\right) \;\le\; D(\mu \,\|\, \nu). $$
This is the elementary deterministic-channel case of the data-processing inequality for an
$f$-divergence: processing the data through any measurable map can only reduce the
KL divergence between the two laws. It is the key contraction step used in Wainwright's proof of
Pinsker's inequality (Exercise 15.6), where one reduces the general KL divergence to the two-cell
Bernoulli case via the indicator push-forward of the level set $\{q \le p\}$.

**Reference.** M. J. Wainwright, *High-Dimensional Statistics: A Non-Asymptotic Viewpoint*,
Cambridge University Press, 2019. Chapter 15 (Minimax lower bounds),
§15.1.3 (Some divergence measures), used in Exercise 15.6 (Pinsker's inequality).

**Proof formalization notes.** Mathlib provides the kernel chain rule `klDiv_compProd_left` but
not the push-forward data-processing inequality, so we add `klDiv_map_le` here as a reusable
`ForMathlib` brick (candidate upstream); it is consumed by `PinskerInequality.lean`. The proof
realizes $\mu \circ f^{-1}$ as a marginal of $\mu \otimes (\text{deterministic } f)$ and runs
through the integral representation of the divergence: writing
$D(\mu\|\nu) = \int \mathrm{klFun}(d\mu/d\nu)\, d\nu$, the push-forward density
$d(\mu \circ f^{-1})/d(\nu \circ f^{-1}) \circ f$ equals the conditional expectation of $d\mu/d\nu$
given the $\sigma$-algebra generated by $f$ (`toReal_rnDeriv_map`), so conditional Jensen for the
convex function $\mathrm{klFun}$ on $[0,\infty)$ (`convexOn_klFun.map_condExp_le`) yields the
inequality. The degenerate cases ($D(\mu\|\nu) = \infty$, or $\mu \not\ll \nu$) are handled
separately by `le_top`.

**Bibliographic comments.** The data-processing inequality for KL divergence (and more generally
for any $f$-divergence) is classical folklore with no single seminal source. The general
$f$-divergence statement and its convexity
proof are due to I. Csiszár, *Information-type measures of difference of probability distributions
and indirect observations*, Studia Scientiarum Mathematicarum Hungarica **2** (1967), 299–318, and
independently S. M. Ali and S. D. Silvey, *A general class of coefficients of divergence of one
distribution from another*, Journal of the Royal Statistical Society, Series B, **28** (1966),
131–142. The KL-specific case is the standard data-processing inequality of information theory; see
T. M. Cover and J. A. Thomas, *Elements of Information Theory*, 2nd ed., Wiley, 2006, Theorem 2.8.1
(data-processing inequality for mutual information / relative entropy).
-/

open MeasureTheory ProbabilityTheory InformationTheory
open scoped ENNReal

namespace Hurst

variable {α β : Type*} {mα : MeasurableSpace α} {mβ : MeasurableSpace β}

/-- **Data-processing inequality for KL divergence under a measurable map.** For a measurable
`f : α → β` and probability measures `μ, ν`, the KL divergence between the push-forwards is at most
the KL divergence between the originals: `klDiv (μ.map f) (ν.map f) ≤ klDiv μ ν`. This is the
standard contraction of an `f`-divergence under a (deterministic) channel; proved from the kernel
chain rule `klDiv_compProd_left` by realizing `μ.map f` as a marginal of `μ ⊗ₘ deterministic f`,
since Mathlib lacks a general data-processing inequality.

**Reference.** Wainwright, *High-Dimensional Statistics: A Non-Asymptotic Viewpoint*,
Cambridge University Press, 2019. Chapter 15 (Minimax lower bounds), §15.1.3 (Some divergence measures). -/
theorem klDiv_map_le {f : α → β} (hf : Measurable f) (μ ν : Measure α)
    [IsProbabilityMeasure μ] [IsProbabilityMeasure ν] :
    klDiv (μ.map f) (ν.map f) ≤ klDiv μ ν := by
  have hm : MeasurableSpace.comap f mβ ≤ mα := hf.comap_le
  haveI : IsProbabilityMeasure (μ.map f) := Measure.isProbabilityMeasure_map hf.aemeasurable
  haveI : IsProbabilityMeasure (ν.map f) := Measure.isProbabilityMeasure_map hf.aemeasurable
  haveI : IsFiniteMeasure (ν.trim hm) := isFiniteMeasure_trim hm
  by_cases hμν : μ ≪ ν
  · have hmap_ac : μ.map f ≪ ν.map f := hμν.map hf
    by_cases hktop : klDiv μ ν = ⊤
    · rw [hktop]; exact le_top
    · -- A finite KL divergence makes `klFun ∘ (dμ/dν)` integrable against `ν`.
      obtain ⟨-, hllr⟩ := klDiv_ne_top_iff.mp hktop
      have hr_int : Integrable (fun x => (μ.rnDeriv ν x).toReal) ν :=
        Measure.integrable_toReal_rnDeriv
      have hh_int : Integrable (fun x => klFun ((μ.rnDeriv ν x).toReal)) ν :=
        (integrable_klFun_rnDeriv_iff hμν).mpr hllr
      have hh_nonneg : (0 : α → ℝ) ≤ᵐ[ν] fun x => klFun ((μ.rnDeriv ν x).toReal) :=
        Filter.Eventually.of_forall fun _ => klFun_nonneg ENNReal.toReal_nonneg
      -- Measurability of the push-forward integrand, for the change of variables.
      have hFmeas : Measurable fun y => ENNReal.ofReal
          (klFun (((μ.map f).rnDeriv (ν.map f) y).toReal)) :=
        ENNReal.measurable_ofReal.comp (continuous_klFun.measurable.comp
          (((μ.map f).measurable_rnDeriv (ν.map f)).ennreal_toReal))
      -- Push-forward density equals the conditional expectation of the original density.
      have hbar_eq : (fun x => ((μ.map f).rnDeriv (ν.map f) (f x)).toReal)
          =ᵐ[ν] ν[fun x => (μ.rnDeriv ν x).toReal | MeasurableSpace.comap f mβ] :=
        toReal_rnDeriv_map hμν hf
      -- Conditional Jensen for the convex `klFun` on `[0, ∞)`.
      have hjensen : (fun x => klFun (ν[fun x => (μ.rnDeriv ν x).toReal |
            MeasurableSpace.comap f mβ] x))
          ≤ᵐ[ν] ν[fun x => klFun ((μ.rnDeriv ν x).toReal) | MeasurableSpace.comap f mβ] :=
        convexOn_klFun.map_condExp_le hm
          (continuous_klFun.lowerSemicontinuous.lowerSemicontinuousOn _)
          (Filter.Eventually.of_forall fun _ => Set.mem_Ici.mpr ENNReal.toReal_nonneg)
          isClosed_Ici hr_int hh_int
      calc klDiv (μ.map f) (ν.map f)
          = ∫⁻ y, ENNReal.ofReal
              (klFun (((μ.map f).rnDeriv (ν.map f) y).toReal)) ∂(ν.map f) :=
            klDiv_eq_lintegral_klFun_of_ac hmap_ac
        _ = ∫⁻ x, ENNReal.ofReal
              (klFun (((μ.map f).rnDeriv (ν.map f) (f x)).toReal)) ∂ν :=
            lintegral_map hFmeas hf
        _ = ∫⁻ x, ENNReal.ofReal
              (klFun (ν[fun x => (μ.rnDeriv ν x).toReal | MeasurableSpace.comap f mβ] x)) ∂ν := by
            refine lintegral_congr_ae ?_
            filter_upwards [hbar_eq] with x hx; rw [hx]
        _ ≤ ∫⁻ x, ENNReal.ofReal
              (ν[fun x => klFun ((μ.rnDeriv ν x).toReal) | MeasurableSpace.comap f mβ] x) ∂ν := by
            refine lintegral_mono_ae ?_
            filter_upwards [hjensen] with x hx
            exact ENNReal.ofReal_le_ofReal hx
        _ = ENNReal.ofReal
              (∫ x, ν[fun x => klFun ((μ.rnDeriv ν x).toReal) | MeasurableSpace.comap f mβ] x ∂ν) :=
            (ofReal_integral_eq_lintegral_ofReal integrable_condExp
              (condExp_nonneg hh_nonneg)).symm
        _ = ENNReal.ofReal (∫ x, klFun ((μ.rnDeriv ν x).toReal) ∂ν) := by
            rw [integral_condExp hm]
        _ = ∫⁻ x, ENNReal.ofReal (klFun ((μ.rnDeriv ν x).toReal)) ∂ν :=
            ofReal_integral_eq_lintegral_ofReal hh_int hh_nonneg
        _ = klDiv μ ν := (klDiv_eq_lintegral_klFun_of_ac hμν).symm
  · rw [klDiv_of_not_ac hμν]; exact le_top

end Hurst
